ktor:
  application:
    modules:
      - io.github.jsixface.codexvert.ApplicationKt.module
  deployment:
    port: "$PORT:8080"
    host: "$BIND:localhost"


database:
  type: "${DB_TYPE}:sqlite"
  url: "${DB_JDBC_URL}:jdbc:sqlite:data/codex.db"
  user: "${DB_USER}:codex"
  password: "${DB_PASSWORD}:password"
